@startuml

!include domain-name.puml
!include top-level-domain.puml

class RegisteredName {
+ Value() String
+ Equals(RegisteredName registeredName) Boolean
-- Constructors --
+ (String topLevelDomain, String domainName)
+ (String registeredName)
}

RegisteredName *-- DomainName
RegisteredName *-- TopLevelDomain

@enduml