@startuml

!include ./domain-name.puml
!include ./top-level-domain.puml

class RegisteredName {
+ Value() string
+ Equals() boolean
-- Constructors --
+ (tld string, domainName string)
+ (registeredName string)
}

RegisteredName *-- DomainName
RegisteredName *-- TopLevelDomain

@enduml