name: Generate Diagrams
on:
  push:
    branches: [ "main" ]
    paths:
      - 'diagrams/**'
      - '.github/workflows/diagrams.yml'
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install -y plantuml
          sudo apt-get install graphviz
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Process Diagrams
        run: java -jar plantuml.jar -v -tsvg -r -o "${{ github.workspace }}/diagrams/generated" "diagrams/**/**.puml"
      - name: Display Diagrams
        run: pwd && ls output
      - name: Commit Diagrams
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m ":rocket: Adding Generated PlantUML Diagrams" || exit 0
      - name: Push Diagrams
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}